name: NUnit Tests

trigger:
- master
- setup-github-pipeline

jobs:
- job: build
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      version: 6.0.x
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    displayName: 'Restore dependencies'
    inputs:
      command: restore

  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: test
      projects: '**/DotNetTestingFramework.csproj'