name: NUnit Tests

on:
  push:
    branches:
      - main [master]
  pull_request:
    branches:
      - main [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'  # Adjust to the version you need

    - name: Restore dependencies
      run: dotnet restore

    - name: Test
      run: dotnet test
