name: NUnit Tests and Deploy Allure Reports

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test
        
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4.0.0
        with:
          name: allure-results
          path: .\bin\Debug\net6.0\allure-results
          if-no-files-found: error
          retention-days: 20
      
      - name: Clean up gh-pages branch (optional)
        run: |
          git checkout -f gh-pages
          git rm -rf .  

  report:
    needs: test  # Ensure previous tests run first
  
    runs-on: ubuntu-latest
  
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4.1.0
        with:
          name: allure-results
          path: ./allure-results
  
      - name: Get Allure history (optional)
        uses: actions/checkout@v4.1.1
        if: always()  # Always check out history for reports
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
  
      - name: Generate report
        uses: simple-elf/allure-report-action@v1.7
        if: always()  # Always generate report
        id: allure-report
        with:
          allure_results: allure-results
          # Deploy the generated report directly
          gh_pages: allure-report
          allure_history: allure-history  # Keep historical reports
          keep_reports: 20
  
      - name: Verify generated report (optional)
        run: |
          cd allure-report
          # Use a local server to preview the report for verification
          serve -s .
  
      - name: Deploy report to Github Pages
        if: always()  # Always deploy generated report
        uses: peaceiris/actions-github-pages@v3.1.12
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          # Deploy the generated report directory
          PUBLISH_DIR: allure-report

