name: NUnit-Tests-Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test
        
      - name: Check current directory
        run: |
              cd bin
              ls
              cd Debug
              ls
              cd net6.0
              ls
              cd allure-results
              ls
        
      - name: Upload Allure Results
        uses: actions/upload-artifact@v3.1.3
        with:
          name: allure-results
          path: /bin/Debug/net6.0/allure-results
          if-no-files-found: fail
          retention-days: 20
